# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22887b4aef36e6ef3673718ebf417e6c80456b63b68d05fdade1d14be263324e2ec6c0cadc2a8b5372e207b5dee2970692ab641488e9b5e779cfa0fc5aa7d36d

test:
  secret_key_base: e9bcbdad378eb92537aaa95095c8742f029818f191c0ab52b5063fa6dd30384c744ce47a8b4aa19c1a9668fd3968938b19711d16eceebf5920db00d59b39a960

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
